<a href="https://colab.research.google.com/github/Jialan8020/ds4ph-bme/blob/master/Assignment8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [5]:
[x_train.shape, y_train.shape, x_test.shape, y_test.shape]

[(60000, 28, 28), (60000,), (10000, 28, 28), (10000,)]

In [0]:
model_1 = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
model_1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               100480    
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_4 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_6 (Dense)              (None, 32)                2080      
_________________________________________________________________
dropout_5 (Dropout)          (None, 32)               

In [22]:
p = model_1(x_test[:1]).numpy()
p

array([[ -6.639034  ,  -0.046375  ,  -0.15426569,   2.5300796 ,
         -4.94511   ,  -5.2550545 , -16.682745  ,  14.282117  ,
         -5.3043146 ,   3.2997618 ]], dtype=float32)

In [23]:
tf.nn.softmax(p).numpy()

array([[8.2044332e-10, 5.9869222e-07, 5.3746169e-07, 7.8730645e-06,
        4.4638586e-09, 3.2741863e-09, 3.5654934e-14, 9.9997389e-01,
        3.1168044e-09, 1.6998572e-05]], dtype=float32)

In [24]:
exp_eta = np.exp(p)
exp_eta / np.sum(exp_eta)

array([[8.2044305e-10, 5.9869240e-07, 5.3746157e-07, 7.8730636e-06,
        4.4638568e-09, 3.2741834e-09, 3.5654971e-14, 9.9997395e-01,
        3.1168046e-09, 1.6998574e-05]], dtype=float32)

In [14]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_test[:1], p).numpy()

2.3351102

In [0]:
model_1.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [26]:
model_1.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1075 - accuracy: 0.9700
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0998 - accuracy: 0.9715
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9743
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0854 - accuracy: 0.9763
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0810 - accuracy: 0.9767


Prediction accuracy for three hidden layers with 128, 64 and 32 nodes respectively:

In [27]:
model_1.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0818 - accuracy: 0.9784


[0.08184192329645157, 0.9783999919891357]

In [0]:
model_2 = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [29]:
model_2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 32)                25120     
_________________________________________________________________
dropout_6 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 10)                330       
Total params: 25,450
Trainable params: 25,450
Non-trainable params: 0
_________________________________________________________________


In [30]:
p_2 = model_2(x_test[:1]).numpy()
p_2

array([[ 0.15376593, -0.24458763, -0.7177256 , -0.18670699,  0.16397461,
         0.5805708 ,  0.4246986 ,  0.46969235, -0.35708103,  0.30009267]],
      dtype=float32)

In [31]:
tf.nn.softmax(p_2).numpy()

array([[0.10220686, 0.0686242 , 0.0427559 , 0.07271341, 0.10325561,
        0.15661706, 0.1340123 , 0.14017971, 0.06132281, 0.11831205]],
      dtype=float32)

In [32]:
exp_eta_2 = np.exp(p_2)
exp_eta_2 / np.sum(exp_eta_2)

array([[0.10220688, 0.06862421, 0.04275591, 0.07271343, 0.10325561,
        0.15661708, 0.13401231, 0.14017974, 0.06132282, 0.11831206]],
      dtype=float32)

In [33]:
loss_fn_2 = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn_2(y_test[:1], p_2).numpy()

1.96483

In [0]:
model_2.compile(optimizer='adam',
              loss=loss_fn_2,
              metrics=['accuracy'])

In [35]:
model_2.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4700 - accuracy: 0.8596
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2780 - accuracy: 0.9181
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2448 - accuracy: 0.9257
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2213 - accuracy: 0.9332
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2077 - accuracy: 0.9362


Prediction accuracy for one hidden layer with 32 nodes:

In [36]:
model_2.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.1391 - accuracy: 0.9572


[0.13912524282932281, 0.9571999907493591]